/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authMonitorRouteRouteImport } from './routes/(auth)/monitor/route'
import { Route as authAdminRouteRouteImport } from './routes/(auth)/admin/route'
import { Route as authMonitorIndexRouteImport } from './routes/(auth)/monitor/index'
import { Route as authAdminIndexRouteImport } from './routes/(auth)/admin/index'
import { Route as authMonitorWorkspacePreviewRouteImport } from './routes/(auth)/monitor/workspace-preview'
import { Route as authMonitorResultsRouteImport } from './routes/(auth)/monitor/results'
import { Route as authMonitorProfileRouteImport } from './routes/(auth)/monitor/profile'
import { Route as authMonitorMonitorsRouteImport } from './routes/(auth)/monitor/monitors'
import { Route as authMonitorAlertsRouteImport } from './routes/(auth)/monitor/alerts'
import { Route as authAdminNewsRouteImport } from './routes/(auth)/admin/news'
import { Route as authAdminChangeMonitorRouteImport } from './routes/(auth)/admin/change-monitor'
import { Route as authAdminSettingsRouteRouteImport } from './routes/(auth)/admin/settings/route'
import { Route as authAdminMonitorRouteRouteImport } from './routes/(auth)/admin/monitor/route'
import { Route as authAdminUsersIndexRouteImport } from './routes/(auth)/admin/users/index'
import { Route as authAdminSettingsIndexRouteImport } from './routes/(auth)/admin/settings/index'
import { Route as authAdminNewsIndexRouteImport } from './routes/(auth)/admin/news/index'
import { Route as authAdminMonitorIndexRouteImport } from './routes/(auth)/admin/monitor/index'
import { Route as authAdminUsersUserIdRouteImport } from './routes/(auth)/admin/users/$userId'
import { Route as authAdminSettingsNotificationsRouteImport } from './routes/(auth)/admin/settings/notifications'
import { Route as authAdminSettingsDisplayRouteImport } from './routes/(auth)/admin/settings/display'
import { Route as authAdminSettingsAppearanceRouteImport } from './routes/(auth)/admin/settings/appearance'
import { Route as authAdminSettingsAccountRouteImport } from './routes/(auth)/admin/settings/account'
import { Route as authAdminMonitorSourcesRouteImport } from './routes/(auth)/admin/monitor/sources'
import { Route as authAdminMonitorResultsRouteImport } from './routes/(auth)/admin/monitor/results'
import { Route as authAdminMonitorProblemsRouteImport } from './routes/(auth)/admin/monitor/problems'
import { Route as authAdminMonitorPickerRouteImport } from './routes/(auth)/admin/monitor/picker'
import { Route as authAdminMonitorMonitorsRouteImport } from './routes/(auth)/admin/monitor/monitors'
import { Route as authAdminMonitorLogsRouteImport } from './routes/(auth)/admin/monitor/logs'
import { Route as authAdminMonitorAlertsRouteImport } from './routes/(auth)/admin/monitor/alerts'
import { Route as authAdminErrorsErrorRouteImport } from './routes/(auth)/admin/errors/$error'
import { Route as authAdminNewsIdIndexRouteImport } from './routes/(auth)/admin/news/$id/index'
import { Route as authAdminMonitorMonitorsIndexRouteImport } from './routes/(auth)/admin/monitor/monitors.index'
import { Route as authAdminNewsIdEditRouteImport } from './routes/(auth)/admin/news/$id/edit'
import { Route as authAdminMonitorMonitorsMonitorIdRouteImport } from './routes/(auth)/admin/monitor/monitors.$monitorId'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authMonitorRouteRoute = authMonitorRouteRouteImport.update({
  id: '/(auth)/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const authAdminRouteRoute = authAdminRouteRouteImport.update({
  id: '/(auth)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authMonitorIndexRoute = authMonitorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authMonitorRouteRoute,
} as any)
const authAdminIndexRoute = authAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authMonitorWorkspacePreviewRoute =
  authMonitorWorkspacePreviewRouteImport.update({
    id: '/workspace-preview',
    path: '/workspace-preview',
    getParentRoute: () => authMonitorRouteRoute,
  } as any)
const authMonitorResultsRoute = authMonitorResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => authMonitorRouteRoute,
} as any)
const authMonitorProfileRoute = authMonitorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authMonitorRouteRoute,
} as any)
const authMonitorMonitorsRoute = authMonitorMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => authMonitorRouteRoute,
} as any)
const authMonitorAlertsRoute = authMonitorAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => authMonitorRouteRoute,
} as any)
const authAdminNewsRoute = authAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authAdminChangeMonitorRoute = authAdminChangeMonitorRouteImport.update({
  id: '/change-monitor',
  path: '/change-monitor',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authAdminSettingsRouteRoute = authAdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authAdminMonitorRouteRoute = authAdminMonitorRouteRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authAdminUsersIndexRoute = authAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authAdminSettingsIndexRoute = authAdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAdminSettingsRouteRoute,
} as any)
const authAdminNewsIndexRoute = authAdminNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAdminNewsRoute,
} as any)
const authAdminMonitorIndexRoute = authAdminMonitorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAdminMonitorRouteRoute,
} as any)
const authAdminUsersUserIdRoute = authAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authAdminSettingsNotificationsRoute =
  authAdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => authAdminSettingsRouteRoute,
  } as any)
const authAdminSettingsDisplayRoute =
  authAdminSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => authAdminSettingsRouteRoute,
  } as any)
const authAdminSettingsAppearanceRoute =
  authAdminSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => authAdminSettingsRouteRoute,
  } as any)
const authAdminSettingsAccountRoute =
  authAdminSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => authAdminSettingsRouteRoute,
  } as any)
const authAdminMonitorSourcesRoute = authAdminMonitorSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => authAdminMonitorRouteRoute,
} as any)
const authAdminMonitorResultsRoute = authAdminMonitorResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => authAdminMonitorRouteRoute,
} as any)
const authAdminMonitorProblemsRoute =
  authAdminMonitorProblemsRouteImport.update({
    id: '/problems',
    path: '/problems',
    getParentRoute: () => authAdminMonitorRouteRoute,
  } as any)
const authAdminMonitorPickerRoute = authAdminMonitorPickerRouteImport.update({
  id: '/picker',
  path: '/picker',
  getParentRoute: () => authAdminMonitorRouteRoute,
} as any)
const authAdminMonitorMonitorsRoute =
  authAdminMonitorMonitorsRouteImport.update({
    id: '/monitors',
    path: '/monitors',
    getParentRoute: () => authAdminMonitorRouteRoute,
  } as any)
const authAdminMonitorLogsRoute = authAdminMonitorLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => authAdminMonitorRouteRoute,
} as any)
const authAdminMonitorAlertsRoute = authAdminMonitorAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => authAdminMonitorRouteRoute,
} as any)
const authAdminErrorsErrorRoute = authAdminErrorsErrorRouteImport.update({
  id: '/errors/$error',
  path: '/errors/$error',
  getParentRoute: () => authAdminRouteRoute,
} as any)
const authAdminNewsIdIndexRoute = authAdminNewsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => authAdminNewsRoute,
} as any)
const authAdminMonitorMonitorsIndexRoute =
  authAdminMonitorMonitorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authAdminMonitorMonitorsRoute,
  } as any)
const authAdminNewsIdEditRoute = authAdminNewsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => authAdminNewsRoute,
} as any)
const authAdminMonitorMonitorsMonitorIdRoute =
  authAdminMonitorMonitorsMonitorIdRouteImport.update({
    id: '/$monitorId',
    path: '/$monitorId',
    getParentRoute: () => authAdminMonitorMonitorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/health': typeof HealthRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/admin': typeof authAdminRouteRouteWithChildren
  '/monitor': typeof authMonitorRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/monitor': typeof authAdminMonitorRouteRouteWithChildren
  '/admin/settings': typeof authAdminSettingsRouteRouteWithChildren
  '/admin/change-monitor': typeof authAdminChangeMonitorRoute
  '/admin/news': typeof authAdminNewsRouteWithChildren
  '/monitor/alerts': typeof authMonitorAlertsRoute
  '/monitor/monitors': typeof authMonitorMonitorsRoute
  '/monitor/profile': typeof authMonitorProfileRoute
  '/monitor/results': typeof authMonitorResultsRoute
  '/monitor/workspace-preview': typeof authMonitorWorkspacePreviewRoute
  '/admin/': typeof authAdminIndexRoute
  '/monitor/': typeof authMonitorIndexRoute
  '/admin/errors/$error': typeof authAdminErrorsErrorRoute
  '/admin/monitor/alerts': typeof authAdminMonitorAlertsRoute
  '/admin/monitor/logs': typeof authAdminMonitorLogsRoute
  '/admin/monitor/monitors': typeof authAdminMonitorMonitorsRouteWithChildren
  '/admin/monitor/picker': typeof authAdminMonitorPickerRoute
  '/admin/monitor/problems': typeof authAdminMonitorProblemsRoute
  '/admin/monitor/results': typeof authAdminMonitorResultsRoute
  '/admin/monitor/sources': typeof authAdminMonitorSourcesRoute
  '/admin/settings/account': typeof authAdminSettingsAccountRoute
  '/admin/settings/appearance': typeof authAdminSettingsAppearanceRoute
  '/admin/settings/display': typeof authAdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof authAdminSettingsNotificationsRoute
  '/admin/users/$userId': typeof authAdminUsersUserIdRoute
  '/admin/monitor/': typeof authAdminMonitorIndexRoute
  '/admin/news/': typeof authAdminNewsIndexRoute
  '/admin/settings/': typeof authAdminSettingsIndexRoute
  '/admin/users/': typeof authAdminUsersIndexRoute
  '/admin/monitor/monitors/$monitorId': typeof authAdminMonitorMonitorsMonitorIdRoute
  '/admin/news/$id/edit': typeof authAdminNewsIdEditRoute
  '/admin/monitor/monitors/': typeof authAdminMonitorMonitorsIndexRoute
  '/admin/news/$id/': typeof authAdminNewsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/health': typeof HealthRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/change-monitor': typeof authAdminChangeMonitorRoute
  '/monitor/alerts': typeof authMonitorAlertsRoute
  '/monitor/monitors': typeof authMonitorMonitorsRoute
  '/monitor/profile': typeof authMonitorProfileRoute
  '/monitor/results': typeof authMonitorResultsRoute
  '/monitor/workspace-preview': typeof authMonitorWorkspacePreviewRoute
  '/admin': typeof authAdminIndexRoute
  '/monitor': typeof authMonitorIndexRoute
  '/admin/errors/$error': typeof authAdminErrorsErrorRoute
  '/admin/monitor/alerts': typeof authAdminMonitorAlertsRoute
  '/admin/monitor/logs': typeof authAdminMonitorLogsRoute
  '/admin/monitor/picker': typeof authAdminMonitorPickerRoute
  '/admin/monitor/problems': typeof authAdminMonitorProblemsRoute
  '/admin/monitor/results': typeof authAdminMonitorResultsRoute
  '/admin/monitor/sources': typeof authAdminMonitorSourcesRoute
  '/admin/settings/account': typeof authAdminSettingsAccountRoute
  '/admin/settings/appearance': typeof authAdminSettingsAppearanceRoute
  '/admin/settings/display': typeof authAdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof authAdminSettingsNotificationsRoute
  '/admin/users/$userId': typeof authAdminUsersUserIdRoute
  '/admin/monitor': typeof authAdminMonitorIndexRoute
  '/admin/news': typeof authAdminNewsIndexRoute
  '/admin/settings': typeof authAdminSettingsIndexRoute
  '/admin/users': typeof authAdminUsersIndexRoute
  '/admin/monitor/monitors/$monitorId': typeof authAdminMonitorMonitorsMonitorIdRoute
  '/admin/news/$id/edit': typeof authAdminNewsIdEditRoute
  '/admin/monitor/monitors': typeof authAdminMonitorMonitorsIndexRoute
  '/admin/news/$id': typeof authAdminNewsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/health': typeof HealthRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/(auth)/admin': typeof authAdminRouteRouteWithChildren
  '/(auth)/monitor': typeof authMonitorRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(auth)/admin/monitor': typeof authAdminMonitorRouteRouteWithChildren
  '/(auth)/admin/settings': typeof authAdminSettingsRouteRouteWithChildren
  '/(auth)/admin/change-monitor': typeof authAdminChangeMonitorRoute
  '/(auth)/admin/news': typeof authAdminNewsRouteWithChildren
  '/(auth)/monitor/alerts': typeof authMonitorAlertsRoute
  '/(auth)/monitor/monitors': typeof authMonitorMonitorsRoute
  '/(auth)/monitor/profile': typeof authMonitorProfileRoute
  '/(auth)/monitor/results': typeof authMonitorResultsRoute
  '/(auth)/monitor/workspace-preview': typeof authMonitorWorkspacePreviewRoute
  '/(auth)/admin/': typeof authAdminIndexRoute
  '/(auth)/monitor/': typeof authMonitorIndexRoute
  '/(auth)/admin/errors/$error': typeof authAdminErrorsErrorRoute
  '/(auth)/admin/monitor/alerts': typeof authAdminMonitorAlertsRoute
  '/(auth)/admin/monitor/logs': typeof authAdminMonitorLogsRoute
  '/(auth)/admin/monitor/monitors': typeof authAdminMonitorMonitorsRouteWithChildren
  '/(auth)/admin/monitor/picker': typeof authAdminMonitorPickerRoute
  '/(auth)/admin/monitor/problems': typeof authAdminMonitorProblemsRoute
  '/(auth)/admin/monitor/results': typeof authAdminMonitorResultsRoute
  '/(auth)/admin/monitor/sources': typeof authAdminMonitorSourcesRoute
  '/(auth)/admin/settings/account': typeof authAdminSettingsAccountRoute
  '/(auth)/admin/settings/appearance': typeof authAdminSettingsAppearanceRoute
  '/(auth)/admin/settings/display': typeof authAdminSettingsDisplayRoute
  '/(auth)/admin/settings/notifications': typeof authAdminSettingsNotificationsRoute
  '/(auth)/admin/users/$userId': typeof authAdminUsersUserIdRoute
  '/(auth)/admin/monitor/': typeof authAdminMonitorIndexRoute
  '/(auth)/admin/news/': typeof authAdminNewsIndexRoute
  '/(auth)/admin/settings/': typeof authAdminSettingsIndexRoute
  '/(auth)/admin/users/': typeof authAdminUsersIndexRoute
  '/(auth)/admin/monitor/monitors/$monitorId': typeof authAdminMonitorMonitorsMonitorIdRoute
  '/(auth)/admin/news/$id/edit': typeof authAdminNewsIdEditRoute
  '/(auth)/admin/monitor/monitors/': typeof authAdminMonitorMonitorsIndexRoute
  '/(auth)/admin/news/$id/': typeof authAdminNewsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/health'
    | '/pricing'
    | '/solutions'
    | '/admin'
    | '/monitor'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/monitor'
    | '/admin/settings'
    | '/admin/change-monitor'
    | '/admin/news'
    | '/monitor/alerts'
    | '/monitor/monitors'
    | '/monitor/profile'
    | '/monitor/results'
    | '/monitor/workspace-preview'
    | '/admin/'
    | '/monitor/'
    | '/admin/errors/$error'
    | '/admin/monitor/alerts'
    | '/admin/monitor/logs'
    | '/admin/monitor/monitors'
    | '/admin/monitor/picker'
    | '/admin/monitor/problems'
    | '/admin/monitor/results'
    | '/admin/monitor/sources'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/admin/users/$userId'
    | '/admin/monitor/'
    | '/admin/news/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/monitor/monitors/$monitorId'
    | '/admin/news/$id/edit'
    | '/admin/monitor/monitors/'
    | '/admin/news/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/health'
    | '/pricing'
    | '/solutions'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/change-monitor'
    | '/monitor/alerts'
    | '/monitor/monitors'
    | '/monitor/profile'
    | '/monitor/results'
    | '/monitor/workspace-preview'
    | '/admin'
    | '/monitor'
    | '/admin/errors/$error'
    | '/admin/monitor/alerts'
    | '/admin/monitor/logs'
    | '/admin/monitor/picker'
    | '/admin/monitor/problems'
    | '/admin/monitor/results'
    | '/admin/monitor/sources'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/admin/users/$userId'
    | '/admin/monitor'
    | '/admin/news'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/monitor/monitors/$monitorId'
    | '/admin/news/$id/edit'
    | '/admin/monitor/monitors'
    | '/admin/news/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/health'
    | '/pricing'
    | '/solutions'
    | '/(auth)/admin'
    | '/(auth)/monitor'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(auth)/admin/monitor'
    | '/(auth)/admin/settings'
    | '/(auth)/admin/change-monitor'
    | '/(auth)/admin/news'
    | '/(auth)/monitor/alerts'
    | '/(auth)/monitor/monitors'
    | '/(auth)/monitor/profile'
    | '/(auth)/monitor/results'
    | '/(auth)/monitor/workspace-preview'
    | '/(auth)/admin/'
    | '/(auth)/monitor/'
    | '/(auth)/admin/errors/$error'
    | '/(auth)/admin/monitor/alerts'
    | '/(auth)/admin/monitor/logs'
    | '/(auth)/admin/monitor/monitors'
    | '/(auth)/admin/monitor/picker'
    | '/(auth)/admin/monitor/problems'
    | '/(auth)/admin/monitor/results'
    | '/(auth)/admin/monitor/sources'
    | '/(auth)/admin/settings/account'
    | '/(auth)/admin/settings/appearance'
    | '/(auth)/admin/settings/display'
    | '/(auth)/admin/settings/notifications'
    | '/(auth)/admin/users/$userId'
    | '/(auth)/admin/monitor/'
    | '/(auth)/admin/news/'
    | '/(auth)/admin/settings/'
    | '/(auth)/admin/users/'
    | '/(auth)/admin/monitor/monitors/$monitorId'
    | '/(auth)/admin/news/$id/edit'
    | '/(auth)/admin/monitor/monitors/'
    | '/(auth)/admin/news/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  HealthRoute: typeof HealthRoute
  PricingRoute: typeof PricingRoute
  SolutionsRoute: typeof SolutionsRoute
  authAdminRouteRoute: typeof authAdminRouteRouteWithChildren
  authMonitorRouteRoute: typeof authMonitorRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/monitor': {
      id: '/(auth)/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof authMonitorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/admin': {
      id: '/(auth)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/monitor/': {
      id: '/(auth)/monitor/'
      path: '/'
      fullPath: '/monitor/'
      preLoaderRoute: typeof authMonitorIndexRouteImport
      parentRoute: typeof authMonitorRouteRoute
    }
    '/(auth)/admin/': {
      id: '/(auth)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authAdminIndexRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/monitor/workspace-preview': {
      id: '/(auth)/monitor/workspace-preview'
      path: '/workspace-preview'
      fullPath: '/monitor/workspace-preview'
      preLoaderRoute: typeof authMonitorWorkspacePreviewRouteImport
      parentRoute: typeof authMonitorRouteRoute
    }
    '/(auth)/monitor/results': {
      id: '/(auth)/monitor/results'
      path: '/results'
      fullPath: '/monitor/results'
      preLoaderRoute: typeof authMonitorResultsRouteImport
      parentRoute: typeof authMonitorRouteRoute
    }
    '/(auth)/monitor/profile': {
      id: '/(auth)/monitor/profile'
      path: '/profile'
      fullPath: '/monitor/profile'
      preLoaderRoute: typeof authMonitorProfileRouteImport
      parentRoute: typeof authMonitorRouteRoute
    }
    '/(auth)/monitor/monitors': {
      id: '/(auth)/monitor/monitors'
      path: '/monitors'
      fullPath: '/monitor/monitors'
      preLoaderRoute: typeof authMonitorMonitorsRouteImport
      parentRoute: typeof authMonitorRouteRoute
    }
    '/(auth)/monitor/alerts': {
      id: '/(auth)/monitor/alerts'
      path: '/alerts'
      fullPath: '/monitor/alerts'
      preLoaderRoute: typeof authMonitorAlertsRouteImport
      parentRoute: typeof authMonitorRouteRoute
    }
    '/(auth)/admin/news': {
      id: '/(auth)/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof authAdminNewsRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/admin/change-monitor': {
      id: '/(auth)/admin/change-monitor'
      path: '/change-monitor'
      fullPath: '/admin/change-monitor'
      preLoaderRoute: typeof authAdminChangeMonitorRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/admin/settings': {
      id: '/(auth)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof authAdminSettingsRouteRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/admin/monitor': {
      id: '/(auth)/admin/monitor'
      path: '/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof authAdminMonitorRouteRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/admin/users/': {
      id: '/(auth)/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof authAdminUsersIndexRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/admin/settings/': {
      id: '/(auth)/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof authAdminSettingsIndexRouteImport
      parentRoute: typeof authAdminSettingsRouteRoute
    }
    '/(auth)/admin/news/': {
      id: '/(auth)/admin/news/'
      path: '/'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof authAdminNewsIndexRouteImport
      parentRoute: typeof authAdminNewsRoute
    }
    '/(auth)/admin/monitor/': {
      id: '/(auth)/admin/monitor/'
      path: '/'
      fullPath: '/admin/monitor/'
      preLoaderRoute: typeof authAdminMonitorIndexRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/users/$userId': {
      id: '/(auth)/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof authAdminUsersUserIdRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/admin/settings/notifications': {
      id: '/(auth)/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof authAdminSettingsNotificationsRouteImport
      parentRoute: typeof authAdminSettingsRouteRoute
    }
    '/(auth)/admin/settings/display': {
      id: '/(auth)/admin/settings/display'
      path: '/display'
      fullPath: '/admin/settings/display'
      preLoaderRoute: typeof authAdminSettingsDisplayRouteImport
      parentRoute: typeof authAdminSettingsRouteRoute
    }
    '/(auth)/admin/settings/appearance': {
      id: '/(auth)/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof authAdminSettingsAppearanceRouteImport
      parentRoute: typeof authAdminSettingsRouteRoute
    }
    '/(auth)/admin/settings/account': {
      id: '/(auth)/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof authAdminSettingsAccountRouteImport
      parentRoute: typeof authAdminSettingsRouteRoute
    }
    '/(auth)/admin/monitor/sources': {
      id: '/(auth)/admin/monitor/sources'
      path: '/sources'
      fullPath: '/admin/monitor/sources'
      preLoaderRoute: typeof authAdminMonitorSourcesRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/monitor/results': {
      id: '/(auth)/admin/monitor/results'
      path: '/results'
      fullPath: '/admin/monitor/results'
      preLoaderRoute: typeof authAdminMonitorResultsRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/monitor/problems': {
      id: '/(auth)/admin/monitor/problems'
      path: '/problems'
      fullPath: '/admin/monitor/problems'
      preLoaderRoute: typeof authAdminMonitorProblemsRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/monitor/picker': {
      id: '/(auth)/admin/monitor/picker'
      path: '/picker'
      fullPath: '/admin/monitor/picker'
      preLoaderRoute: typeof authAdminMonitorPickerRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/monitor/monitors': {
      id: '/(auth)/admin/monitor/monitors'
      path: '/monitors'
      fullPath: '/admin/monitor/monitors'
      preLoaderRoute: typeof authAdminMonitorMonitorsRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/monitor/logs': {
      id: '/(auth)/admin/monitor/logs'
      path: '/logs'
      fullPath: '/admin/monitor/logs'
      preLoaderRoute: typeof authAdminMonitorLogsRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/monitor/alerts': {
      id: '/(auth)/admin/monitor/alerts'
      path: '/alerts'
      fullPath: '/admin/monitor/alerts'
      preLoaderRoute: typeof authAdminMonitorAlertsRouteImport
      parentRoute: typeof authAdminMonitorRouteRoute
    }
    '/(auth)/admin/errors/$error': {
      id: '/(auth)/admin/errors/$error'
      path: '/errors/$error'
      fullPath: '/admin/errors/$error'
      preLoaderRoute: typeof authAdminErrorsErrorRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
    '/(auth)/admin/news/$id/': {
      id: '/(auth)/admin/news/$id/'
      path: '/$id'
      fullPath: '/admin/news/$id/'
      preLoaderRoute: typeof authAdminNewsIdIndexRouteImport
      parentRoute: typeof authAdminNewsRoute
    }
    '/(auth)/admin/monitor/monitors/': {
      id: '/(auth)/admin/monitor/monitors/'
      path: '/'
      fullPath: '/admin/monitor/monitors/'
      preLoaderRoute: typeof authAdminMonitorMonitorsIndexRouteImport
      parentRoute: typeof authAdminMonitorMonitorsRoute
    }
    '/(auth)/admin/news/$id/edit': {
      id: '/(auth)/admin/news/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof authAdminNewsIdEditRouteImport
      parentRoute: typeof authAdminNewsRoute
    }
    '/(auth)/admin/monitor/monitors/$monitorId': {
      id: '/(auth)/admin/monitor/monitors/$monitorId'
      path: '/$monitorId'
      fullPath: '/admin/monitor/monitors/$monitorId'
      preLoaderRoute: typeof authAdminMonitorMonitorsMonitorIdRouteImport
      parentRoute: typeof authAdminMonitorMonitorsRoute
    }
  }
}

interface authAdminMonitorMonitorsRouteChildren {
  authAdminMonitorMonitorsMonitorIdRoute: typeof authAdminMonitorMonitorsMonitorIdRoute
  authAdminMonitorMonitorsIndexRoute: typeof authAdminMonitorMonitorsIndexRoute
}

const authAdminMonitorMonitorsRouteChildren: authAdminMonitorMonitorsRouteChildren =
  {
    authAdminMonitorMonitorsMonitorIdRoute:
      authAdminMonitorMonitorsMonitorIdRoute,
    authAdminMonitorMonitorsIndexRoute: authAdminMonitorMonitorsIndexRoute,
  }

const authAdminMonitorMonitorsRouteWithChildren =
  authAdminMonitorMonitorsRoute._addFileChildren(
    authAdminMonitorMonitorsRouteChildren,
  )

interface authAdminMonitorRouteRouteChildren {
  authAdminMonitorAlertsRoute: typeof authAdminMonitorAlertsRoute
  authAdminMonitorLogsRoute: typeof authAdminMonitorLogsRoute
  authAdminMonitorMonitorsRoute: typeof authAdminMonitorMonitorsRouteWithChildren
  authAdminMonitorPickerRoute: typeof authAdminMonitorPickerRoute
  authAdminMonitorProblemsRoute: typeof authAdminMonitorProblemsRoute
  authAdminMonitorResultsRoute: typeof authAdminMonitorResultsRoute
  authAdminMonitorSourcesRoute: typeof authAdminMonitorSourcesRoute
  authAdminMonitorIndexRoute: typeof authAdminMonitorIndexRoute
}

const authAdminMonitorRouteRouteChildren: authAdminMonitorRouteRouteChildren = {
  authAdminMonitorAlertsRoute: authAdminMonitorAlertsRoute,
  authAdminMonitorLogsRoute: authAdminMonitorLogsRoute,
  authAdminMonitorMonitorsRoute: authAdminMonitorMonitorsRouteWithChildren,
  authAdminMonitorPickerRoute: authAdminMonitorPickerRoute,
  authAdminMonitorProblemsRoute: authAdminMonitorProblemsRoute,
  authAdminMonitorResultsRoute: authAdminMonitorResultsRoute,
  authAdminMonitorSourcesRoute: authAdminMonitorSourcesRoute,
  authAdminMonitorIndexRoute: authAdminMonitorIndexRoute,
}

const authAdminMonitorRouteRouteWithChildren =
  authAdminMonitorRouteRoute._addFileChildren(
    authAdminMonitorRouteRouteChildren,
  )

interface authAdminSettingsRouteRouteChildren {
  authAdminSettingsAccountRoute: typeof authAdminSettingsAccountRoute
  authAdminSettingsAppearanceRoute: typeof authAdminSettingsAppearanceRoute
  authAdminSettingsDisplayRoute: typeof authAdminSettingsDisplayRoute
  authAdminSettingsNotificationsRoute: typeof authAdminSettingsNotificationsRoute
  authAdminSettingsIndexRoute: typeof authAdminSettingsIndexRoute
}

const authAdminSettingsRouteRouteChildren: authAdminSettingsRouteRouteChildren =
  {
    authAdminSettingsAccountRoute: authAdminSettingsAccountRoute,
    authAdminSettingsAppearanceRoute: authAdminSettingsAppearanceRoute,
    authAdminSettingsDisplayRoute: authAdminSettingsDisplayRoute,
    authAdminSettingsNotificationsRoute: authAdminSettingsNotificationsRoute,
    authAdminSettingsIndexRoute: authAdminSettingsIndexRoute,
  }

const authAdminSettingsRouteRouteWithChildren =
  authAdminSettingsRouteRoute._addFileChildren(
    authAdminSettingsRouteRouteChildren,
  )

interface authAdminNewsRouteChildren {
  authAdminNewsIndexRoute: typeof authAdminNewsIndexRoute
  authAdminNewsIdEditRoute: typeof authAdminNewsIdEditRoute
  authAdminNewsIdIndexRoute: typeof authAdminNewsIdIndexRoute
}

const authAdminNewsRouteChildren: authAdminNewsRouteChildren = {
  authAdminNewsIndexRoute: authAdminNewsIndexRoute,
  authAdminNewsIdEditRoute: authAdminNewsIdEditRoute,
  authAdminNewsIdIndexRoute: authAdminNewsIdIndexRoute,
}

const authAdminNewsRouteWithChildren = authAdminNewsRoute._addFileChildren(
  authAdminNewsRouteChildren,
)

interface authAdminRouteRouteChildren {
  authAdminMonitorRouteRoute: typeof authAdminMonitorRouteRouteWithChildren
  authAdminSettingsRouteRoute: typeof authAdminSettingsRouteRouteWithChildren
  authAdminChangeMonitorRoute: typeof authAdminChangeMonitorRoute
  authAdminNewsRoute: typeof authAdminNewsRouteWithChildren
  authAdminIndexRoute: typeof authAdminIndexRoute
  authAdminErrorsErrorRoute: typeof authAdminErrorsErrorRoute
  authAdminUsersUserIdRoute: typeof authAdminUsersUserIdRoute
  authAdminUsersIndexRoute: typeof authAdminUsersIndexRoute
}

const authAdminRouteRouteChildren: authAdminRouteRouteChildren = {
  authAdminMonitorRouteRoute: authAdminMonitorRouteRouteWithChildren,
  authAdminSettingsRouteRoute: authAdminSettingsRouteRouteWithChildren,
  authAdminChangeMonitorRoute: authAdminChangeMonitorRoute,
  authAdminNewsRoute: authAdminNewsRouteWithChildren,
  authAdminIndexRoute: authAdminIndexRoute,
  authAdminErrorsErrorRoute: authAdminErrorsErrorRoute,
  authAdminUsersUserIdRoute: authAdminUsersUserIdRoute,
  authAdminUsersIndexRoute: authAdminUsersIndexRoute,
}

const authAdminRouteRouteWithChildren = authAdminRouteRoute._addFileChildren(
  authAdminRouteRouteChildren,
)

interface authMonitorRouteRouteChildren {
  authMonitorAlertsRoute: typeof authMonitorAlertsRoute
  authMonitorMonitorsRoute: typeof authMonitorMonitorsRoute
  authMonitorProfileRoute: typeof authMonitorProfileRoute
  authMonitorResultsRoute: typeof authMonitorResultsRoute
  authMonitorWorkspacePreviewRoute: typeof authMonitorWorkspacePreviewRoute
  authMonitorIndexRoute: typeof authMonitorIndexRoute
}

const authMonitorRouteRouteChildren: authMonitorRouteRouteChildren = {
  authMonitorAlertsRoute: authMonitorAlertsRoute,
  authMonitorMonitorsRoute: authMonitorMonitorsRoute,
  authMonitorProfileRoute: authMonitorProfileRoute,
  authMonitorResultsRoute: authMonitorResultsRoute,
  authMonitorWorkspacePreviewRoute: authMonitorWorkspacePreviewRoute,
  authMonitorIndexRoute: authMonitorIndexRoute,
}

const authMonitorRouteRouteWithChildren =
  authMonitorRouteRoute._addFileChildren(authMonitorRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  HealthRoute: HealthRoute,
  PricingRoute: PricingRoute,
  SolutionsRoute: SolutionsRoute,
  authAdminRouteRoute: authAdminRouteRouteWithChildren,
  authMonitorRouteRoute: authMonitorRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
